### ISSUE TITLE
No violar SOLID - SR

### ISSUE THREAD

**Issue by AyudantesTecnicas** [swandelow/template-tp-grupal#10]
Single Responsibility 
En general los comandos tienen mas de una responsabilidad, resolver la acción y armar la respuesta a mostrar al jugador.
Por ejemplo: “LookAround” además de ver que objetos hay, resuelve como se debe mostrar el mensaje de respuesta al cliente, seria mejor devolver la lista de objetos, y que otro decida como mostrar la respuesta, separando dichas responsabilidades. Ver como mejorar esto.

public class Stage {
…..

public String lookAround() {
   StringBuilder sb = new StringBuilder();
   sb.append(String.format("Items in the %s: ", this.getName()));
   Iterator<Item> it = itemContainer.getAllItems().iterator();
   while (it.hasNext()) {
       sb.append(it.next().getName());
       if (it.hasNext()) {
           sb.append(", ");
       } else {
           sb.append(".");
       }
   }
   return sb.toString();
}

**Comment by esantamarta** [comment]
Se le dio solución implementando la clase ItemKeeperView que realiza el lookAround en los ItemKeeper (por ejemplo un Stage, un Box, etc). La clase Stage, por ejemplo, ahora realiza un new de la clase ItemKeeperView y luego ejecuta el metodo print, encargado de mostrar los objetos del Stage.
