### ISSUE TITLE
Completar pendientes Entrega 3

### ISSUE THREAD

**Issue by AyudantesTecnicas** [swandelow/template-tp-grupal#16]
- Implementar Completo el Juego Escape 2
- Hacer Tests teniendo en cuenta el Random y Tiempo

**Comment by swandelow** [comment]
- Implementamos abstracciones que encapsulan la lógica del Timer y Random.
- Implementamos los tests de aceptación pedidos.
- Corregimos la condición que hace perder a un jugador al entrar al la biblioteca sin autorización.
- Hicimos fixes varios en el engine y builder.
