### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AyudantesTecnicas** [swandelow/template-tp-grupal#7]
Les paso algo de feedback de lo que vi:

La documentación me pareció buena y completa.

A nivel arquitectura, dado que lo que se construye es un motor de juegos, con el fin de poder crear nuevos juegos y que otros puedan crear nuevos juegos, no parece muy bueno mezclar conceptos del motor con conceptos del juego particular. Vemos que hay subpaquetes para cada juego, pero sería mejor separar en distintos proyectos, cosa que quede bien claro y pueda separar, distribuir solo el motor, de los juegos en si que hacen uso o extienden el motor. 
Pudiendo quedar en componentes físicos separados (.jar), para que un jar sea solo el motor, y los juegos puntuales puedan ser agregados en nuevos componentes físicos a medida que se crean.
Incluso server y cliente podría ser componentes físicos separados también.

El diseño de esta primer entrega, requiere codificar nuevas clases extendiendo al motor, esta opción es una opción válida y muy usada en muchos frameworks, para los requerimientos de la primer entrega parece un diseño válido, lo único que lo que se observa en las clases de cada juego están casi vacías o que tienen código repetido entre sí (Ejemplo Sheep, Wolf) y suena que entre muchos juegos esto puede pasar, y es verdad que se puede generalizar en el modelo del motor e incluir mas clases a medida que aparecen nuevos juegos. Lo importante de esta decisión es saber que pros y contras nos puede traer frente a otras opciones. 

Trataría de separar responsabildades de los mensajes de respuesta de un comando de lo que hace el comando, se estaría violando SR en esos casos.

En general me pareció bueno, trataría de que lo generalicen mas, logrando abstracciones que permitan crear los Items y configurarlos agregándoles estados y acciones, pero sin necesidad de crear nuevas clases concretas o mismo sin necesidad de crear un juego concreto sino de poder configurarlo.

**Comment by keynaka** [comment]
- Se ha logrado la separacion fisica de los juegos en .jar. 
- Se ha logrado mas generalizacion dejando de lado los items concretos como Key, Door, Disk. Se ha programado para que a estos se le puedan setear  sus Estados, Rules que seria lo que deben cumplir para ejecutarse detereminadas acciones y las Acciones que realizaria el cambio de estado.
- Se ha separado la responsabilidad de los mensajes de respuesta.
